// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webkho_20241021.Models;

#nullable disable

namespace Webkho_20241021.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117130215_AddPricingColumnsToVoucherDetails")]
    partial class AddPricingColumnsToVoucherDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Webkho_20241021.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bophan")
                        .HasColumnType("longtext");

                    b.Property<string>("Chucvu")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.Property<string>("manv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Webkho_20241021.Models.duans", b =>
                {
                    b.Property<string>("MaDuan")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("KhachHang")
                        .HasColumnType("longtext");

                    b.Property<string>("MaNguoiQLDA")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayBatdau")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayKetthuc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NguoiQLDA")
                        .HasColumnType("longtext");

                    b.Property<string>("TenDuan")
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext");

                    b.HasKey("MaDuan");

                    b.ToTable("duans");
                });

            modelBuilder.Entity("Webkho_20241021.Models.khoduans", b =>
                {
                    b.Property<string>("DAMaDuan")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DAMakho")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DonVi")
                        .HasColumnType("longtext");

                    b.Property<string>("HangSX")
                        .HasColumnType("longtext");

                    b.Property<string>("MaSanpham")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayBaohanh")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayNhapkho")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NhaCC")
                        .HasColumnType("longtext");

                    b.Property<int?>("SL")
                        .HasColumnType("int");

                    b.Property<string>("TenSanpham")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ThoiGianBH")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext");

                    b.HasKey("DAMaDuan", "DAMakho");

                    b.ToTable("khoduans");
                });

            modelBuilder.Entity("Webkho_20241021.Models.khonguoidungs", b =>
                {
                    b.Property<string>("NDMaNguoidung")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NDMakho")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DonVi")
                        .HasColumnType("longtext");

                    b.Property<string>("HangSX")
                        .HasColumnType("longtext");

                    b.Property<string>("MaSanpham")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayBaohanh")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayNhapkho")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NhaCC")
                        .HasColumnType("longtext");

                    b.Property<int?>("SL")
                        .HasColumnType("int");

                    b.Property<string>("TenSanpham")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ThoiGianBH")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext");

                    b.HasKey("NDMaNguoidung", "NDMakho");

                    b.ToTable("khonguoidungs");
                });

            modelBuilder.Entity("Webkho_20241021.Models.khotongs", b =>
                {
                    b.Property<string>("Makho")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DonVi")
                        .HasColumnType("longtext");

                    b.Property<string>("DuAn")
                        .HasColumnType("longtext");

                    b.Property<string>("HangSX")
                        .HasColumnType("longtext");

                    b.Property<string>("LoaiCapPhat")
                        .HasColumnType("longtext");

                    b.Property<string>("MaSanpham")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayBaohanh")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayNhapkho")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NhaCC")
                        .HasColumnType("longtext");

                    b.Property<int?>("SL")
                        .HasColumnType("int");

                    b.Property<string>("TenSanpham")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ThoiGianBH")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext");

                    b.HasKey("Makho");

                    b.ToTable("khotongs");
                });

            modelBuilder.Entity("Webkho_20241021.Models.nguoidungs", b =>
                {
                    b.Property<string>("MaNguoidung")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Bophan")
                        .HasColumnType("longtext");

                    b.Property<string>("Chucvu")
                        .HasColumnType("longtext");

                    b.Property<string>("TenNguoidung")
                        .HasColumnType("longtext");

                    b.HasKey("MaNguoidung");

                    b.ToTable("nguoidungs");
                });

            modelBuilder.Entity("Webkho_20241021.Models.phieumuahang", b =>
                {
                    b.Property<string>("MaMuahang")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaYeucau")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<string>("MaDuan")
                        .HasColumnType("longtext");

                    b.Property<string>("MaNguoidung")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayMuahang")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext");

                    b.HasKey("MaMuahang", "MaYeucau");

                    b.ToTable("phieumuahang");
                });

            modelBuilder.Entity("Webkho_20241021.Models.phieunhapkho", b =>
                {
                    b.Property<string>("MaNhapkho")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaYeucau")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaDuan")
                        .HasColumnType("longtext");

                    b.Property<string>("MaNguoidung")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayNhapkho")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext");

                    b.HasKey("MaNhapkho", "MaYeucau");

                    b.ToTable("phieunhapkho");
                });

            modelBuilder.Entity("Webkho_20241021.Models.phieuxuatkho", b =>
                {
                    b.Property<string>("MaXuatkho")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaYeucau")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<string>("MaDuan")
                        .HasColumnType("longtext");

                    b.Property<string>("MaNguoidung")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayChuanBi")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgaySanSang")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayXacNhanNhan")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayXuatkho")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext");

                    b.HasKey("MaXuatkho", "MaYeucau");

                    b.ToTable("phieuxuatkho");
                });

            modelBuilder.Entity("Webkho_20241021.Models.vtphieumuahang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonVi")
                        .HasColumnType("longtext");

                    b.Property<string>("GhiChu")
                        .HasColumnType("longtext");

                    b.Property<string>("HangSX")
                        .HasColumnType("longtext");

                    b.Property<string>("MaMuahang")
                        .HasColumnType("longtext");

                    b.Property<string>("MaSanpham")
                        .HasColumnType("longtext");

                    b.Property<string>("MaYeucau")
                        .HasColumnType("longtext");

                    b.Property<string>("Makho")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayBaohanh")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayNhapkho")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NhaCC")
                        .HasColumnType("longtext");

                    b.Property<int?>("SL")
                        .HasColumnType("int");

                    b.Property<string>("TenSanpham")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ThoiGianBH")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("vtphieumuahang");
                });

            modelBuilder.Entity("Webkho_20241021.Models.vtphieunhapkho", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonVi")
                        .HasColumnType("longtext");

                    b.Property<string>("HangSX")
                        .HasColumnType("longtext");

                    b.Property<string>("MaNhapkho")
                        .HasColumnType("longtext");

                    b.Property<string>("MaSanpham")
                        .HasColumnType("longtext");

                    b.Property<string>("MaYeucau")
                        .HasColumnType("longtext");

                    b.Property<string>("Makho")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayBaohanh")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayNhapkho")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NhaCC")
                        .HasColumnType("longtext");

                    b.Property<int?>("SL")
                        .HasColumnType("int");

                    b.Property<string>("TenSanpham")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ThoiGianBH")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("vtphieunhapkho");
                });

            modelBuilder.Entity("Webkho_20241021.Models.vtphieuxuatkho", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonVi")
                        .HasColumnType("longtext");

                    b.Property<string>("HangSX")
                        .HasColumnType("longtext");

                    b.Property<string>("LoaiCapPhat")
                        .HasColumnType("longtext");

                    b.Property<string>("MaSanpham")
                        .HasColumnType("longtext");

                    b.Property<string>("MaXuatkho")
                        .HasColumnType("longtext");

                    b.Property<string>("MaYeucau")
                        .HasColumnType("longtext");

                    b.Property<string>("Makho")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayBaohanh")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayNhapkho")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NhaCC")
                        .HasColumnType("longtext");

                    b.Property<int?>("SL")
                        .HasColumnType("int");

                    b.Property<string>("TenSanpham")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ThoiGianBH")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("vtphieuxuatkho");
                });

            modelBuilder.Entity("Webkho_20241021.Models.vtyeucau", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DonVi")
                        .HasColumnType("longtext");

                    b.Property<string>("HangSX")
                        .HasColumnType("longtext");

                    b.Property<string>("MaSanpham")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayBaohanh")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayNhapkho")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NhaCC")
                        .HasColumnType("longtext");

                    b.Property<int?>("SL")
                        .HasColumnType("int");

                    b.Property<string>("TenSanpham")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ThoiGianBH")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext");

                    b.Property<string>("VTMaYeucau")
                        .HasColumnType("longtext");

                    b.Property<string>("YCMakho")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("vtyeucau");
                });

            modelBuilder.Entity("Webkho_20241021.Models.yeucau", b =>
                {
                    b.Property<string>("MaYeucau")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Bophan")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayYeucau")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NguoiYeucau")
                        .HasColumnType("longtext");

                    b.Property<string>("TenYeucau")
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext");

                    b.Property<string>("YCMaDuan")
                        .HasColumnType("longtext");

                    b.Property<string>("YCMaNguoidung")
                        .HasColumnType("longtext");

                    b.HasKey("MaYeucau");

                    b.ToTable("yeucau");
                });
#pragma warning restore 612, 618
        }
    }
}
