name: Deploy khostu .NET 8 to IIS
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - run: dotnet restore
      - run: dotnet build --configuration Release
      - run: dotnet publish -c Release -o ./publish

      - name: Stop IIS AppPool
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            powershell -Command "Import-Module WebAdministration; Stop-WebAppPool webkho"

      - name: Clean old files
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            powershell -Command "Remove-Item -Recurse -Force 'C:\inetpub\wwwroot\Webkho20241021'; New-Item -ItemType Directory -Force -Path 'C:\inetpub\wwwroot\Webkho20241021'"

      - name: Upload to Windows VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./publish/*"
          target: "C:/inetpub/wwwroot/Webkho20241021"

      - name: Start IIS AppPool
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            powershell -Command "Import-Module WebAdministration; Start-WebAppPool webkho; Write-Host '✅ IIS AppPool webkho restarted'"
